### PR TITLE
I208 upgrade search trials

### PR DESCRIPTION
**Pull request by davimang**
- Indicate when a trial is selected/hovered (just chose a random style rn)
- Add load more trials instead of prev/next page (note: didn't bother styling loading symbol, figured @deep123845  would end up changing it when he does the styling changes)
- Ability to fetch any chunk of trials, but still only render a subset of those trials (rn just fetching 5, and rendering 3 of the 5, then 2, then 3, etc... if we were fetching 20, we could easily render 5 each time, or any number less than 20)
- Add brief description if detailed description is not present
- Fix map rendering each time something is selected

### CODE REVIEW

**Comment by deep123845** [comment]
I am only able to load 5 trials on certain profiles before the more trials button stops functioning. The first time I click more trials it works as expected, the second time it shows the loading symbol for a second but does not load any additional trials. Also this is in the console for the API: 
image
It also seems to depend on the profile as for another profile I got to 90 trials before the same issue happened. Might be related to running out of trials for the given search.

**Comment by deep123845** [comment]
Pressing the search button multiple times on the same profile seems to the same trials to be added to the list. I pressed the search button twice on the same trial and trials 1-5 were identical to trials 6-10.
image
image

**Comment by davimang** [comment]
@deep123845 was aware of the second bug (thats what im fixing rn). Will look into the first issue after I fix this one.

**Comment by deep123845** [comment]
Profile for api error: 
image

**Pull request merged**
