### PR TITLE
Feature error display

### PR DESCRIPTION
**Pull request by deep123845**
Added error displays for most fields on login, registration, and profile creation page.

Most field validation only checks if the field is empty.

Username validation on registration page checks if username is already in use.
Email validation checks if it is in valid email format
Address validation checks if street, city, province and postal code are inputted (even if empty ex. "a, ,a , " is a valid address.

Submit buttons are disabled if fields are not valid.

-On profile creation page condition and advanced info validation is not currently implemented.

### CODE REVIEW

**Comment by davimang** [comment]
Can/should the login button be greyed out if no username/password is entered yet?

**Comment by deep123845** [comment]
Right now if it is working, the login button only disables if there is no username. I can make it check if the password is empty too, or I can make it always enabled. I am not sure which would be better what do you think?
@davimang

**Comment by davimang** [comment]
@deep123845 Hmm, I was thinking it would be good if the login button was grey until there is something typed in both the username & password field. Also, I think rn it initially loads green, and only turns grey when u like 'skip' entering a username. If it could load as grey initially, then when u type in both fields, turn green, I think that would be good. Lmk if u think of something better/if there is anything wrong with this idea.

**Comment by deep123845** [comment]
Should be fixed now, when I was testing chrome autofilled the username and pass so I didn't see that it would be useable even if it loaded empty. Login page should check for both username and pass now. Also added some error displays if the form fails to submit for any other reason. The button should also change faster on most fields now. @davimang

**Comment by davimang** [comment]
Cool, looks good to me. If u have nothing else to implement, should be good to merge 👍

**Pull request merged**
